apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - canary.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
